### ISSUE TITLE
Stereo expand mode

### ISSUE THREAD

**Issue by bjtftw** [h1data/foo_dsp_width#1]
Hello, how about adding ability to also expand stereo instead of only narrowing it? 
It's a matter of adding scale >100% probably only but I don't have any Windows machine to compile this to binary (I'm using foobar2000 on Linux)

**Comment by h1data** [comment]
Thanks for your feedback.
It needs to verify if 100%+ works with the current formula.
This component is intended only to narrow, but some other components might expand.

**Comment by h1data** [comment]
note to self:
According to the article below, it is necessary to use another formula when the width is 100%+.
https://www.musicdsp.org/en/latest/Effects/256-stereo-width-control-obtained-via-transfromation-matrix.html

I'd like to refer to the algorithm because it uses less multiplication per sample,
but it has to consider the width parameter scale. (currently exponential)

**Comment by h1data** [comment]
@bjtftw Stereo expander feature is now online.
https://github.com/h1data/foo_dsp_width/releases/tag/v.1.2.0
I'm glad to hear if it works in your environment.

**Comment by bjtftw** [comment]
> @bjtftw  I'm glad to hear if it works in your environment.

YES it works! Man I wasn't expecting this to be done so fast but here it goes :) Sounds great! Thank you!

**Comment by h1data** [comment]
I did not have an idea it works on Linux (Wine maybe?).
Again, thanks for your feedback!
